version: "3.9"
services:
  web:
    image: dstdcie17/hr-api-cie:1.1
    container_name: hr-api-cie
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://20.93.150.129:5432/hr_db?connection_limit=30&pool_timeout=20&connect_timeout=10&statement_cache_size=0
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin225
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_GENERATE_DDL=true
    ports:
      - "8090:8090"
  # Service de base de données locale supprimé - utilise maintenant la BD distante sur 20.93.150.129
