version: "3.9"
services:
  web:
    build:
      context: .
      args:
        VERSION: dev
    container_name: hr-api-cie-local
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://20.93.150.129:5432/hr_db?connection_limit=30&pool_timeout=20&connect_timeout=10&statement_cache_size=0
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin225
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_PROFILES_ACTIVE=prod
      - jwt.secret=NeOu0RusDp05/8gE9wfFdwa0kLgcvrqTTV6cz5eEDEt9ZTwsqIBuTyDntLlDyaEIv8SEuvt4w4rbW3NmnW3v+w==
      - SPRING_MAIL_PASSWORD=P@55w0rd2025
    ports:
      - "8090:8090"
  # Service de base de données locale supprimé - utilise maintenant la BD distante sur 20.93.150.129
