version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: hr-db-local
    environment:
      - POSTGRES_DB=hr_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    ports:
      - "5434:5432"
    volumes:
      - hr_db_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hr_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      args:
        VERSION: dev
    container_name: hr-api-cie-local
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hr_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_PROFILES_ACTIVE=prod
      - jwt.secret=NeOu0RusDp05/8gE9wfFdwa0kLgcvrqTTV6cz5eEDEt9ZTwsqIBuTyDntLlDyaEIv8SEuvt4w4rbW3NmnW3v+w==
      - SPRING_MAIL_PASSWORD=P@55w0rd2025
    ports:
      - "8090:8090"

volumes:
  hr_db_data:
